/***************************************************************************
  timelagsettingsdialog.cpp
  -------------------
  Copyright © 2013-2018, LI-COR Biosciences, Antonio Forgione
  Copyright © 2026,      ETH Zurich, Jonathan Muller

  This file is part of EddyFlow®.

  EddyFlow (TM) is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version. You should have received a copy
  of the GNU General Public License along with EddyFlow (R). If not,
  see <http://www.gnu.org/licenses/>.

  EddyFlow® contains additional Open Source Components. The licenses
  and/or notices these Components can be found in the file LIBRARIES.txt.

  EddyFlow® is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.
****************************************************************************/

#include "timelagsettingsdialog.h"

#include <QButtonGroup>
#include <QCheckBox>
#include <QDateEdit>
#include <QDebug>
#include <QDoubleSpinBox>
#include <QEvent>
#include <QGridLayout>
#include <QPushButton>
#include <QRadioButton>
#include <QSpinBox>

#include "ancillaryfiletest.h"
#include "clicklabel.h"
#include "configstate.h"
#include "customclearlineedit.h"
#include "ecproject.h"
#include "measurement_record.h"
#include "filebrowsewidget.h"
#include "globalsettings.h"
#include "widget_utils.h"

TimeLagSettingsDialog::TimeLagSettingsDialog(QWidget *parent, EcProject *ecProject, ConfigState* config) :
    QDialog(parent),
    ecProject_(ecProject),
    configState_(config)
{
    setWindowModality(Qt::WindowModal);
    setWindowTitle(tr("Time Lag Optimization Settings"));
    WidgetUtils::removeContextHelpButton(this);

    auto groupTitle = new QLabel;
    groupTitle->setText(tr("Configure smart time lag detection, "
                           "providing quality selection criteria and initial "
                           "time lag windows"));

    auto hrLabel = new QLabel;
    hrLabel->setObjectName(QStringLiteral("hrLabel"));

    existingRadio = new QRadioButton(tr("Time lag file available : "));
    existingRadio->setToolTip(tr("<b>Time lag file available:</b> If you have a satisfactory time lag assessment from a previous run and it applies to the current dataset, you can use it by providing the path to the file 'EddyFlow_timelag_opt_ID.txt' that was generated by EddyFlow in the previous run and contains the results of the assessment. This will shorten program execution time and assure full comparability between the current and previous results."));

    nonExistingRadio = new QRadioButton(tr("Time lag file not available :"));
    nonExistingRadio->setToolTip(tr("<b>Time lag file not available:</b> Choose this option and provide the following information if you need to optimize time lags for your dataset. EddyFlow will complete the time lag optimization first and then complete the raw data processing and flux computation procedures."));

    subsetCheckBox = new QCheckBox;
    subsetCheckBox->setProperty("subperiod", true);
    subsetCheckBox->setText(tr("Select a different period"));
    subsetCheckBox->setToolTip(tr("<b>Select a different period:</b> Select this option and set the corresponding dates, to identify the time period EddyFlow will use for the Time lag optimization. This subperiod must fall within the time period defined by the available raw data."));

    startDateLabel = new ClickLabel(this);
    startDateLabel->setText(tr("Start :"));
    startDateLabel->setToolTip(tr("<b>Start:</b> Starting date of the time period to be used for time lag optimization. This time should not be shorter than about 1-2 months. As a general recommendation, select a time period during which the instrument setup did not undergo major modifications. Results obtained using a given time period (e.g., 2 months) can be used for processing a longer time period, in which major modifications did not occur in the setup. The stricter the threshold setup in this dialogue, the longer the period should be in order to get robust results."));
    startDateEdit = new QDateEdit;
    startDateEdit->setToolTip(startDateLabel->toolTip());
    startDateEdit->setCalendarPopup(true);
    WidgetUtils::customizeCalendar(startDateEdit->calendarWidget());

    startTimeEdit = new QTimeEdit;
    startTimeEdit->setDisplayFormat(QStringLiteral("hh:mm"));
    startTimeEdit->setAccelerated(true);

    lockedIcon = new QLabel;
    auto pixmap = QPixmap(QStringLiteral(":/icons/vlink-locked"));
#if defined(Q_OS_MACOS)
    pixmap.setDevicePixelRatio(2.0);
#endif
    lockedIcon->setPixmap(pixmap);

    endDateLabel = new ClickLabel(this);
    endDateLabel->setText(tr("End :"));
    endDateLabel->setToolTip(tr("<b>End:</b> End date of the time period to be used for time lag optimization. This time should not be shorter than about 1-2 months As a general recommendation, select a time period during which the instrumental setup did not undergo major modifications. Results obtained using a given time period (e.g., 2 months) can be used for processing a longer time period, in which major modifications did not occur in the setup. The stricter the threshold setup in this dialogue, the longer the period should be in order to get robust results."));
    endDateEdit = new QDateEdit;
    endDateEdit->setToolTip(endDateLabel->toolTip());
    endDateEdit->setCalendarPopup(true);
    WidgetUtils::customizeCalendar(endDateEdit->calendarWidget());

    endTimeEdit = new QTimeEdit;
    endTimeEdit->setDisplayFormat(QStringLiteral("hh:mm"));
    endTimeEdit->setAccelerated(true);

    auto dateTimeContainer = new QGridLayout;
    dateTimeContainer->addWidget(startDateEdit, 0, 1);
    dateTimeContainer->addWidget(startTimeEdit, 0, 2);
    dateTimeContainer->addWidget(lockedIcon, 0, 0, 2, 1);
    dateTimeContainer->addWidget(endDateEdit, 1, 1);
    dateTimeContainer->addWidget(endTimeEdit, 1, 2);
    dateTimeContainer->setColumnStretch(1, 1);
    dateTimeContainer->setColumnStretch(2, 1);
    dateTimeContainer->setColumnStretch(3, 2);
    dateTimeContainer->setContentsMargins(0, 0, 0, 0);
    dateTimeContainer->setVerticalSpacing(3);

    fileBrowse = new FileBrowseWidget;
    fileBrowse->setToolTip(tr("<b>Load:</b> Load an existing time lag file"));
    fileBrowse->setDialogTitle(tr("Select the Time Lag Optimization File"));
    fileBrowse->setDialogWorkingDir(WidgetUtils::getDialogPathHint(QStringLiteral("timelag_file")));
    fileBrowse->setDialogFilter(tr("All Files (*.*)"));

    auto existingFileLayout = new QHBoxLayout;
    existingFileLayout->addWidget(existingRadio);
    existingFileLayout->addWidget(fileBrowse);
    existingFileLayout->setStretch(2, 1);
    existingFileLayout->setContentsMargins(0, 0, 0, 0);
    existingFileLayout->setSpacing(0);

    radioGroup = new QButtonGroup(this);
    radioGroup->addButton(existingRadio, 0);
    radioGroup->addButton(nonExistingRadio, 1);

    h2oTitleLabel = WidgetUtils::createBlueLabel(this, tr("Water vapor time lag as a function of relative humidity"));

    pgRangeLabel = new ClickLabel(tr("Plausibility range around median value :"));
    pgRangeLabel->setToolTip(tr("<b>Plausibility range around median value:</b> The plausibility range is defined as the median time lag, %1 <i>n</i> times the MAD (median of the absolute deviations from the median time lag). Specify <i>n</i> here. The value of 1.5 was heuristically found to be optimal.").arg(Defs::PLUSMINUS));
    pgRangeSpin = new QDoubleSpinBox;
    pgRangeSpin->setDecimals(1);
    pgRangeSpin->setRange(0.1, 100.0);
    pgRangeSpin->setSingleStep(0.1);
    pgRangeSpin->setAccelerated(true);
    pgRangeSpin->setSuffix(tr("  [mad]"));
    pgRangeSpin->setToolTip(pgRangeLabel->toolTip());
    pgRangeLabel_2 = new QLabel(tr("(<tt>%1%2n%3mad</tt>, where you set <tt>n</tt>)").arg(Defs::MICRO, Defs::PLUSMINUS, Defs::MID_DOT));

    rhClassLabel = new ClickLabel(tr("Number of RH classes :"));
    rhClassLabel->setToolTip(tr("<b>Number of RH classes:</b> Select the number or relative humidity classes, to assess water vapor time lag as a function of RH. The whole range or RH variation (0-100%) will be evenly divided according to the selected number of classes. For example, selecting 10 classes causes EddyFlow to assess water vapor time lags for the classes 0-10%, 10-20%,..., 90-100%. Selecting 1 class, the label <b><i>Do not sort in RH classes</i></b> appears and will cause EddyFlow to treat water vapor exactly like other passive gases. This option is only suitable for open path systems, or closed path systems with short and heated sampling lines."));

    rhClassSpin = new QSpinBox;
    rhClassSpin->setRange(1, 20);
    rhClassSpin->setSingleStep(1);
    rhClassSpin->setAccelerated(true);
    rhClassSpin->setSpecialValueText(tr("Do not sort in RH classes"));
    rhClassSpin->setToolTip(rhClassLabel->toolTip());

    gasTitleLabel = WidgetUtils::createBlueLabel(this, tr("Passive gases"));

    // The gas minimum-flux rows and the search-window header are placed in
    // rebuildGasRows(): their grid rows depend on how many gases the project
    // has, so they cannot be laid out at fixed positions here.

    leMinFluxLabel = new ClickLabel(tr("Minimum latent heat flux :"));
    leMinFluxLabel->setToolTip(tr("<b>Minimum latent heat flux:</b> Minimum latent heat flux: H<sub>2</sub>O time lags corresponding to latent heat fluxes smaller than this value will not be considered in the time lag optimization. Selecting high-enough fluxes assures that well developed turbulent conditions are met and the correlation function is well characterized."));
    leMinFluxSpin = new QDoubleSpinBox;
    leMinFluxSpin->setDecimals(1);
    leMinFluxSpin->setRange(0.0, 1000.0);
    leMinFluxSpin->setSingleStep(0.1);
    leMinFluxSpin->setAccelerated(true);
    leMinFluxSpin->setSuffix(tr("  [%1]").arg(Defs::W_M2_STRING));
    leMinFluxSpin->setToolTip(leMinFluxLabel->toolTip());

    searchWindowLabel = WidgetUtils::createBlueLabel(this, tr("Time lag searching windows"));

    minLabel = WidgetUtils::createBlueLabel(this, tr("Minimum"));
    minLabel->setToolTip(tr("<b>Minimum:</b> Minimum time lag for each gas, for initializing the time lag optimization procedure. The searching window defined by Minimum and Maximum should be large enough to accommodate all possible time lags. Leave as <i>Not set</i> if in doubt, EddyFlow will initialize it automatically."));

    maxLabel = WidgetUtils::createBlueLabel(this, tr("Maximum"));
    maxLabel->setToolTip(tr("<b>Maximum:</b> Maximum time lag for each gas, for initializing the time lag optimization procedure. The searching window defined by Minimum and Maximum should be large enough to accommodate all possible time lags. In particular, maximum time lags of water vapor in closed path systems can up to ten times higher than its nominal value, or even higher. Leave as <i>Not set</i> if in doubt, EddyFlow will initialize it automatically."));

    // Rows are built from the project's gases in rebuildTlRows(), so the
    // dialog follows whatever the site selected rather than a fixed four.
    minSpinTip_ = minLabel->toolTip();
    maxSpinTip_ = maxLabel->toolTip();

    auto propertiesLayout = new QGridLayout;
    propertiesLayout->addLayout(existingFileLayout, 0, 0, 1, -1);
    propertiesLayout->addWidget(nonExistingRadio, 1, 0);
    propertiesLayout->addWidget(subsetCheckBox, 1, 1, 1, 1, Qt::AlignLeft);
    propertiesLayout->addWidget(startDateLabel, 1, 1, Qt::AlignRight);
    propertiesLayout->addLayout(dateTimeContainer, 1, 2, 2, 1);
    propertiesLayout->addWidget(endDateLabel, 2, 1, Qt::AlignRight);
    propertiesLayout->addWidget(pgRangeLabel, 3, 1, 1, 1, Qt::AlignRight);
    propertiesLayout->addWidget(pgRangeSpin, 3, 2);
    propertiesLayout->addWidget(pgRangeLabel_2, 3, 3);

    propertiesLayout->addWidget(h2oTitleLabel, 4, 0, 1, 2);

    propertiesLayout->addWidget(rhClassLabel, 5, 1, Qt::AlignRight);
    propertiesLayout->addWidget(rhClassSpin, 5, 2);
    propertiesLayout->addWidget(leMinFluxLabel, 6, 1, Qt::AlignRight);
    propertiesLayout->addWidget(leMinFluxSpin, 6, 2);

    propertiesLayout->addWidget(gasTitleLabel, 7, 0);

    propertiesLayout_ = propertiesLayout;
    propertiesLayout->setVerticalSpacing(3);
    propertiesLayout->setRowMinimumHeight(2, 10);
    propertiesLayout->setContentsMargins(3, 3, 3, 3);

    auto propertiesFrame = new QWidget;
    propertiesFrame->setLayout(propertiesLayout);
    propertiesFrame->setMinimumWidth(propertiesFrame->sizeHint().width());

    auto okButton = WidgetUtils::createCommonButton(this, tr("Ok"));

    auto mainLayout = new QGridLayout(this);
    mainLayout->addWidget(groupTitle, 0, 0);
    mainLayout->addWidget(hrLabel, 1, 0);
    mainLayout->addWidget(propertiesFrame, 2, 0);
    mainLayout->addWidget(okButton, 3, 0, 1, 1, Qt::AlignCenter);
    mainLayout->setVerticalSpacing(10);
    mainLayout->setContentsMargins(30, 30, 30, 30);
    mainLayout->setSizeConstraint(QLayout::SetFixedSize);
    setLayout(mainLayout);

    connect(radioGroup, &QButtonGroup::idClicked,
            this, &TimeLagSettingsDialog::updateTlMode);

    connect(radioGroup, &QButtonGroup::idClicked,
            this, &TimeLagSettingsDialog::radioClicked);

    connect(fileBrowse, &FileBrowseWidget::pathChanged,
            this, &TimeLagSettingsDialog::updateFile);
    connect(fileBrowse, &FileBrowseWidget::pathSelected,
        this, &TimeLagSettingsDialog::testSelectedFile);

    connect(subsetCheckBox, &QCheckBox::toggled,
            this, &TimeLagSettingsDialog::updateSubsetSelection);

    connect(startDateLabel, &ClickLabel::clicked,
            this, &TimeLagSettingsDialog::onStartDateLabelClicked);
    connect(startDateEdit, &QDateEdit::dateChanged,
            this, &TimeLagSettingsDialog::updateStartDate);
    connect(startTimeEdit, &QTimeEdit::timeChanged,
            this, &TimeLagSettingsDialog::updateStartTime);

    connect(endDateLabel, &ClickLabel::clicked,
            this, &TimeLagSettingsDialog::onEndDateLabelClicked);
    connect(endDateEdit, &QDateEdit::dateChanged,
            this, &TimeLagSettingsDialog::updateEndDate);
    connect(endTimeEdit, &QTimeEdit::timeChanged,
            this, &TimeLagSettingsDialog::updateEndTime);

    connect(rhClassLabel, &ClickLabel::clicked,
            this, &TimeLagSettingsDialog::onRhClassClicked);
    connect(rhClassSpin, QOverload<int>::of(&QSpinBox::valueChanged),
            this, &TimeLagSettingsDialog::updateRhClass);




    connect(leMinFluxLabel, &ClickLabel::clicked,
            this, &TimeLagSettingsDialog::onLeMinFluxClicked);
    connect(leMinFluxSpin, QOverload<double>::of(&QDoubleSpinBox::valueChanged),
            this, &TimeLagSettingsDialog::updateLeMinFlux);

    connect(pgRangeLabel, &ClickLabel::clicked,
            this, &TimeLagSettingsDialog::onPgRangeLabelClicked);
    connect(pgRangeSpin, QOverload<double>::of(&QDoubleSpinBox::valueChanged),
            this, &TimeLagSettingsDialog::updatePgRange);





    connect(okButton, &QPushButton::clicked,
            this, &TimeLagSettingsDialog::close);

    // init
    forceEndDatePolicy();
    forceEndTimePolicy();
}

TimeLagSettingsDialog::~TimeLagSettingsDialog()
{
}

void TimeLagSettingsDialog::close()
{
    if (isVisible())
        hide();
    emit saveRequest();
}

void TimeLagSettingsDialog::reset()
{
    updateTlMode(1);

    existingRadio->setChecked(false);
    nonExistingRadio->setChecked(true);
    fileBrowse->clear();
    subsetCheckBox->setChecked(false);

    startDateEdit->setDate(QDate::fromString(ecProject_->generalStartDate(), Qt::ISODate));
    startTimeEdit->setTime(QTime::fromString(ecProject_->generalStartTime(), QStringLiteral("hh:mm")));
    endDateEdit->setDate(QDate::fromString(ecProject_->generalEndDate(), Qt::ISODate));
    endTimeEdit->setTime(QTime::fromString(ecProject_->generalEndTime(), QStringLiteral("hh:mm")));
    forceEndDatePolicy();
    forceEndTimePolicy();
    updateSubsetSelection(false);

    pgRangeSpin->setValue(1.5);
    rhClassSpin->setValue(10);
    leMinFluxSpin->setValue(20.0);


    radioClicked(1);
}

void TimeLagSettingsDialog::partialRefresh()
{
    // save the modified flag to prevent side effects of setting widgets
    bool oldmod = ecProject_->modified();
    ecProject_->blockSignals(true);

    subsetCheckBox->setChecked(ecProject_->timelagOptSubset());
    if (ecProject_->timelagOptSubset())
    {
        startDateEdit->setDate(QDate::fromString(ecProject_->timelagOptStartDate(), Qt::ISODate));
        startTimeEdit->setTime(QTime::fromString(ecProject_->timelagOptStartTime(), QStringLiteral("hh:mm")));
        endDateEdit->setDate(QDate::fromString(ecProject_->timelagOptEndDate(), Qt::ISODate));
        endTimeEdit->setTime(QTime::fromString(ecProject_->timelagOptEndTime(), QStringLiteral("hh:mm")));
    }
    else
    {
        startDateEdit->setDate(QDate::fromString(ecProject_->generalStartDate(), Qt::ISODate));
        startTimeEdit->setTime(QTime::fromString(ecProject_->generalStartTime(), QStringLiteral("hh:mm")));
        endDateEdit->setDate(QDate::fromString(ecProject_->generalEndDate(), Qt::ISODate));
        endTimeEdit->setTime(QTime::fromString(ecProject_->generalEndTime(), QStringLiteral("hh:mm")));
    }

    // restore modified flag
    ecProject_->setModified(oldmod);
    ecProject_->blockSignals(false);
}

void TimeLagSettingsDialog::refresh()
{
    // save the modified flag to prevent side effects of setting widgets
    bool oldmod = ecProject_->modified();
    ecProject_->blockSignals(true);

    existingRadio->setChecked(!ecProject_->timelagOptMode());
    nonExistingRadio->setChecked(ecProject_->timelagOptMode());

    rebuildGasRows();

    fileBrowse->setPath(ecProject_->timelagOptFile());

    subsetCheckBox->setChecked(ecProject_->timelagOptSubset());
    if (ecProject_->timelagOptSubset())
    {
        startDateEdit->setDate(QDate::fromString(ecProject_->timelagOptStartDate(), Qt::ISODate));
        startTimeEdit->setTime(QTime::fromString(ecProject_->timelagOptStartTime(), QStringLiteral("hh:mm")));
        endDateEdit->setDate(QDate::fromString(ecProject_->timelagOptEndDate(), Qt::ISODate));
        endTimeEdit->setTime(QTime::fromString(ecProject_->timelagOptEndTime(), QStringLiteral("hh:mm")));
    }
    else
    {
        startDateEdit->setDate(QDate::fromString(ecProject_->generalStartDate(), Qt::ISODate));
        startTimeEdit->setTime(QTime::fromString(ecProject_->generalStartTime(), QStringLiteral("hh:mm")));
        endDateEdit->setDate(QDate::fromString(ecProject_->generalEndDate(), Qt::ISODate));
        endTimeEdit->setTime(QTime::fromString(ecProject_->generalEndTime(), QStringLiteral("hh:mm")));
    }

    rhClassSpin->setValue(ecProject_->timelagOptH2oNClass());
    leMinFluxSpin->setValue(ecProject_->timelagOptLeMinFlux());
    pgRangeSpin->setValue(ecProject_->timelagOptPgRange());


    radioClicked(ecProject_->timelagOptMode());

    // restore modified flag
    ecProject_->setModified(oldmod);
    ecProject_->blockSignals(false);
}

void TimeLagSettingsDialog::setDateRange(FileUtils::DateRange dates)
{
    if (!ecProject_->timelagOptSubset())
    {
        startDateEdit->setDate(dates.first.date());
        endDateEdit->setDate(dates.second.date());
    }
}

void TimeLagSettingsDialog::updateTlMode(int radioButton)
{
    ecProject_->setTimelagOptMode(radioButton);
}

void TimeLagSettingsDialog::radioClicked(int radioButton)
{
    if (radioButton == 0)
    {
        fileBrowse->setEnabled(true);
        subsetCheckBox->setEnabled(false);
        startDateLabel->setEnabled(false);
        startDateEdit->setEnabled(false);
        lockedIcon->setEnabled(false);
        endDateLabel->setEnabled(false);
        endDateEdit->setEnabled(false);
        rhClassLabel->setEnabled(false);
        rhClassSpin->setEnabled(false);
        leMinFluxLabel->setEnabled(false);
        leMinFluxSpin->setEnabled(false);
        pgRangeLabel->setEnabled(false);
        pgRangeLabel_2->setEnabled(false);
        pgRangeSpin->setEnabled(false);
        setGasRowsEnabled(false);
    }
    else
    {
        fileBrowse->setEnabled(false);
        subsetCheckBox->setEnabled(true);
        startDateLabel->setEnabled(subsetCheckBox->isChecked());
        startDateEdit->setEnabled(subsetCheckBox->isChecked());
        lockedIcon->setEnabled(subsetCheckBox->isChecked());
        endDateLabel->setEnabled(subsetCheckBox->isChecked());
        endDateEdit->setEnabled(subsetCheckBox->isChecked());
        rhClassLabel->setEnabled(true);
        rhClassSpin->setEnabled(true);
        leMinFluxLabel->setEnabled(true);
        leMinFluxSpin->setEnabled(true);
        pgRangeLabel->setEnabled(true);
        pgRangeLabel_2->setEnabled(true);
        pgRangeSpin->setEnabled(true);
        setGasRowsEnabled(true);
    }
}

/// One time-lag search window per configured gas.
///
/// The first four records also mirror the flat timelagOpt*Lag keys, so an
/// older version reads the same windows and a project written by one keeps
/// its values. Gases past the fourth live only in the record.
void TimeLagSettingsDialog::rebuildGasRows()
{
    if (!propertiesLayout_ || !ecProject_) { return; }

    for (const auto& row : minFluxRows_)
    {
        if (row.label) { row.label->deleteLater(); }
        if (row.spin) { row.spin->deleteLater(); }
    }
    minFluxRows_.clear();
    for (const auto& row : tlRows_)
    {
        if (row.label) { row.label->deleteLater(); }
        if (row.minSpin) { row.minSpin->deleteLater(); }
        if (row.maxSpin) { row.maxSpin->deleteLater(); }
    }
    tlRows_.clear();

    const auto& gases = ecProject_->gasColumns();
    const auto gasName = [&](int i)
    {
        auto text = gases.at(i).slug.toUpper();
        if (MeasurementRecords::isRealInstrument(gases.at(i).instrumentId))
        {
            text += QStringLiteral(" (") + gases.at(i).instrumentId
                    + QStringLiteral(")");
        }
        return text;
    };

    // Both tables and the header between them are placed here, because the
    // header's grid row depends on how many minimum-flux rows precede it.
    int gridRow = kFirstGasGridRow;

    for (int i = 0; i < gases.size(); ++i)
    {
        // A record with no column is a slot kept for ordering, not a
        // measurement. H2O is excluded: its threshold is the latent-heat one
        // in the H2O section, not a gas flux.
        if (gases.at(i).rawColumn <= 0) { continue; }
        if (gases.at(i).slug == QLatin1String("h2o")) { continue; }

        MinFluxRow row;
        row.gasIndex = i;
        row.label = new ClickLabel(
            tr("Minimum (absolute) %1 flux :").arg(gasName(i)));
        row.label->setToolTip(
            tr("<b>Minimum (absolute) %1 flux:</b> %1 time lags corresponding "
               "to fluxes smaller (in module) than this value will not be "
               "considered in the time lag optimization. Selecting high-enough "
               "fluxes assures that well developed turbulent conditions are met "
               "and the correlation function is well characterized.")
                .arg(gasName(i)));

        row.spin = new QDoubleSpinBox;
        row.spin->setDecimals(3);
        row.spin->setRange(0.0, 100.0);
        row.spin->setSingleStep(0.001);
        row.spin->setAccelerated(true);
        row.spin->setSuffix(tr("  [%1]").arg(Defs::UMOL_M2S_STRING));
        row.spin->setToolTip(row.label->toolTip());
        row.spin->setValue(minFluxFor(i));

        propertiesLayout_->addWidget(row.label, gridRow, 1, Qt::AlignRight);
        propertiesLayout_->addWidget(row.spin, gridRow, 2);

        const int idx = i;
        auto spin = row.spin;
        connect(row.label, &ClickLabel::clicked, this, [=]()
                { spin->setFocus(); spin->selectAll(); });
        connect(row.spin, QOverload<double>::of(&QDoubleSpinBox::valueChanged),
                this, [=](double v) { onMinFluxChanged(idx, v); });

        minFluxRows_.append(row);
        ++gridRow;
    }

    propertiesLayout_->addWidget(searchWindowLabel, gridRow, 0);
    ++gridRow;
    propertiesLayout_->addWidget(minLabel, gridRow, 1);
    propertiesLayout_->addWidget(maxLabel, gridRow, 2);
    ++gridRow;

    for (int i = 0; i < gases.size(); ++i)
    {
        if (gases.at(i).rawColumn <= 0) { continue; }

        TlRow row;
        row.gasIndex = i;
        row.minSpin = createTlSpin(true);
        row.maxSpin = createTlSpin(false);
        row.label = new ClickLabel(tr("%1 :").arg(gasName(i)));

        propertiesLayout_->addWidget(row.label, gridRow, 0, Qt::AlignRight);
        propertiesLayout_->addWidget(row.minSpin, gridRow, 1);
        propertiesLayout_->addWidget(row.maxSpin, gridRow, 2);

        row.minSpin->setValue(tlMinFor(i));
        row.maxSpin->setValue(tlMaxFor(i));

        const int idx = i;
        auto minSpin = row.minSpin;
        connect(row.label, &ClickLabel::clicked, this, [=]()
                { minSpin->setFocus(); minSpin->selectAll(); });
        connect(row.minSpin, QOverload<double>::of(&QDoubleSpinBox::valueChanged),
                this, [=](double v) { onTlChanged(idx, true, v); });
        connect(row.maxSpin, QOverload<double>::of(&QDoubleSpinBox::valueChanged),
                this, [=](double v) { onTlChanged(idx, false, v); });

        tlRows_.append(row);
        ++gridRow;
    }
}

void TimeLagSettingsDialog::onMinFluxChanged(int gasIndex, double value)
{
    if (!ecProject_) { return; }
    auto gases = ecProject_->gasColumns();
    if (gasIndex < 0 || gasIndex >= gases.size()) { return; }

    gases[gasIndex].proc.toMinFlux = value;
    ecProject_->setGasColumns(gases);

    switch (gasIndex)
    {
        case 0: ecProject_->setTimelagOptCo2MinFlux(value); break;
        case 2: ecProject_->setTimelagOptCh4MinFlux(value); break;
        case 3: ecProject_->setTimelagOptGas4MinFlux(value); break;
        default: break;   // slot 1 is H2O, which has no gas-flux threshold
    }
}

double TimeLagSettingsDialog::minFluxFor(int gasIndex) const
{
    const auto& gases = ecProject_->gasColumns();
    if (gasIndex >= 0 && gasIndex < gases.size()
        && gases.at(gasIndex).proc.toMinFlux >= 0.0)
    {
        return gases.at(gasIndex).proc.toMinFlux;
    }
    switch (gasIndex)
    {
        case 0: return ecProject_->timelagOptCo2MinFlux();
        case 2: return ecProject_->timelagOptCh4MinFlux();
        case 3: return ecProject_->timelagOptGas4MinFlux();
        default: return 0.0;
    }
}

QDoubleSpinBox* TimeLagSettingsDialog::createTlSpin(bool isMin)
{
    auto spin = new QDoubleSpinBox;
    spin->setDecimals(1);
    spin->setRange(-1000.1, 1000.0);
    spin->setSingleStep(0.1);
    spin->setSpecialValueText(tr("Detect automatically"));
    spin->setAccelerated(true);
    spin->setSuffix(tr("  [s]"));
    spin->setToolTip(isMin ? minSpinTip_ : maxSpinTip_);
    return spin;
}

void TimeLagSettingsDialog::setGasRowsEnabled(bool enabled)
{
    for (const auto& row : minFluxRows_)
    {
        if (row.label) { row.label->setEnabled(enabled); }
        if (row.spin) { row.spin->setEnabled(enabled); }
    }
    for (const auto& row : tlRows_)
    {
        if (row.label) { row.label->setEnabled(enabled); }
        if (row.minSpin) { row.minSpin->setEnabled(enabled); }
        if (row.maxSpin) { row.maxSpin->setEnabled(enabled); }
    }
}

void TimeLagSettingsDialog::onTlChanged(int gasIndex, bool isMin, double value)
{
    if (!ecProject_) { return; }
    auto gases = ecProject_->gasColumns();
    if (gasIndex < 0 || gasIndex >= gases.size()) { return; }

    if (isMin) { gases[gasIndex].proc.toMinLag = value; }
    else       { gases[gasIndex].proc.toMaxLag = value; }
    ecProject_->setGasColumns(gases);

    switch (gasIndex)
    {
        case 0: if (isMin) { ecProject_->setTimelagOptCo2MinLag(value); }
                else       { ecProject_->setTimelagOptCo2MaxLag(value); } break;
        case 1: if (isMin) { ecProject_->setTimelagOptH2oMinLag(value); }
                else       { ecProject_->setTimelagOptH2oMaxLag(value); } break;
        case 2: if (isMin) { ecProject_->setTimelagOptCh4MinLag(value); }
                else       { ecProject_->setTimelagOptCh4MaxLag(value); } break;
        case 3: if (isMin) { ecProject_->setTimelagOptGas4MinLag(value); }
                else       { ecProject_->setTimelagOptGas4MaxLag(value); } break;
        default: break;
    }
}

double TimeLagSettingsDialog::tlMinFor(int gasIndex) const
{
    const auto& gases = ecProject_->gasColumns();
    if (gasIndex >= 0 && gasIndex < gases.size()
        && gases.at(gasIndex).proc.toMinLag > -9000.0
        && gases.at(gasIndex).proc.toMinLag != -1.0)
    {
        return gases.at(gasIndex).proc.toMinLag;
    }
    switch (gasIndex)
    {
        case 0: return ecProject_->timelagOptCo2MinLag();
        case 1: return ecProject_->timelagOptH2oMinLag();
        case 2: return ecProject_->timelagOptCh4MinLag();
        case 3: return ecProject_->timelagOptGas4MinLag();
        default: return -1000.1;
    }
}

double TimeLagSettingsDialog::tlMaxFor(int gasIndex) const
{
    const auto& gases = ecProject_->gasColumns();
    if (gasIndex >= 0 && gasIndex < gases.size()
        && gases.at(gasIndex).proc.toMaxLag > -9000.0
        && gases.at(gasIndex).proc.toMaxLag != -1.0)
    {
        return gases.at(gasIndex).proc.toMaxLag;
    }
    switch (gasIndex)
    {
        case 0: return ecProject_->timelagOptCo2MaxLag();
        case 1: return ecProject_->timelagOptH2oMaxLag();
        case 2: return ecProject_->timelagOptCh4MaxLag();
        case 3: return ecProject_->timelagOptGas4MaxLag();
        default: return -1000.1;
    }
}

void TimeLagSettingsDialog::onStartDateLabelClicked()
{
    startDateEdit->setFocus();
    WidgetUtils::showCalendarOf(startDateEdit);
}

void TimeLagSettingsDialog::onEndDateLabelClicked()
{
    endDateEdit->setFocus();
    WidgetUtils::showCalendarOf(endDateEdit);
}

void TimeLagSettingsDialog::updateStartDate(const QDate &d)
{
    ecProject_->setTimelagOptStartDate(d.toString(Qt::ISODate));
    forceEndDatePolicy();
}

void TimeLagSettingsDialog::updateStartTime(const QTime& t)
{
    ecProject_->setTimelagOptStartTime(t.toString(QStringLiteral("hh:mm")));
    forceEndTimePolicy();
}

void TimeLagSettingsDialog::updateEndDate(const QDate &d)
{
    ecProject_->setTimelagOptEndDate(d.toString(Qt::ISODate));
}


void TimeLagSettingsDialog::updateEndTime(const QTime& t)
{
    ecProject_->setTimelagOptEndTime(t.toString(QStringLiteral("hh:mm")));
}

// enforce (start date&time) <= (end date&time)
void TimeLagSettingsDialog::forceEndDatePolicy()
{
    endDateEdit->setMinimumDate(startDateEdit->date());
}


// enforce (start date&time) <= (end date&time)
void TimeLagSettingsDialog::forceEndTimePolicy()
{
    if (startDateEdit->date() == endDateEdit->date())
    {
        endTimeEdit->setMinimumTime(startTimeEdit->time());
    }
    else
    {
        endTimeEdit->clearMinimumTime();
    }
}

void TimeLagSettingsDialog::updateFile(const QString& fp)
{
    ecProject_->setTimelagOptFile(QDir::cleanPath(fp));
}

void TimeLagSettingsDialog::testSelectedFile(const QString& fp)
{
    if (fp.isEmpty()) { return; }

    QFileInfo paramFilePath(fp);
    QString canonicalParamFile = paramFilePath.canonicalFilePath();

    AncillaryFileTest test_dialog(AncillaryFileTest::FileType::TimeLag, ecProject_, this);
    test_dialog.refresh(canonicalParamFile);

    auto test_result = test_dialog.makeTest();

    auto dialog_result = true;

    // blocking behavior if test fails
    if (!test_result)
    {
        dialog_result = test_dialog.exec();
    }

    if (dialog_result)
    {
        fileBrowse->setPath(canonicalParamFile);
        WidgetUtils::rememberDialogPath(QStringLiteral("timelag_file"), canonicalParamFile, true);
        WidgetUtils::rememberDialogPath(QStringLiteral("timelag_import_file"), canonicalParamFile, true);
    }
    else
    {
        fileBrowse->clear();
    }
}

void TimeLagSettingsDialog::onRhClassClicked()
{
    rhClassSpin->setFocus();
    rhClassSpin->selectAll();
}

void TimeLagSettingsDialog::updateRhClass(int n)
{
    ecProject_->setTimelagOptH2oNClass(n);
}







void TimeLagSettingsDialog::onLeMinFluxClicked()
{
    leMinFluxSpin->setFocus();
    leMinFluxSpin->selectAll();
}

void TimeLagSettingsDialog::updateLeMinFlux(double d)
{
    ecProject_->setTimelagOptLeMinFlux(d);
}

void TimeLagSettingsDialog::onPgRangeLabelClicked()
{
    pgRangeSpin->setFocus();
    pgRangeSpin->selectAll();
}

void TimeLagSettingsDialog::updatePgRange(double d)
{
    ecProject_->setTimelagOptPgRange(d);
}













void TimeLagSettingsDialog::updateSubsetSelection(bool b)
{
    ecProject_->setTimelagOptSubset(b);

    auto widget_list = QWidgetList() << startDateLabel
                                     << startDateEdit
                                     << startTimeEdit
                                     << lockedIcon
                                     << endDateLabel
                                     << endDateEdit
                                     << endTimeEdit;
    for (auto w : widget_list)
    {
        w->setEnabled(b);
    }
}

void TimeLagSettingsDialog::setSmartfluxUI()
{
    bool on = configState_->project.smartfluxMode;

    nonExistingRadio->setDisabled(on);

    // block project modified() signal
    auto oldmod = false;
    if (!on)
    {
        // save the modified flag to prevent side effects of setting widgets
        oldmod = ecProject_->modified();
        ecProject_->blockSignals(true);
    }

    if (on)
    {
        radioGroup->button(0)->click();
    }

    // restore project modified() signal
    if (!on)
    {
        // restore modified flag
        ecProject_->setModified(oldmod);
        ecProject_->blockSignals(false);
    }
}

